### PR TITLE
crocodile defconfig += rauc

### PR DESCRIPTION
**Pull request by js731ca**
cleanup the defconfig, and add rauc specific switches

### CODE REVIEW

**Review by zandrey — COMMENTED** [review]
Please extend the description of 6a0849f2d4b4e1722e19b9858e67bbd92ade0029 with the link that lists necessary config options for _RAUC_ integration (this can be found in the _RAUC_ Manual).

**Review by zandrey — CHANGES_REQUESTED** [review]
Thank for the link!

What I see after you pushed the new 4b4292cc7483b0403f798c4d9f98b1e4ffeba351, `CONFIG_CRYPTO_SHA256` is missing.

Is it intended?

If not - please add it as well, according to what is required by _RAUC_ and stated in the Manual.

**Comment by zandrey** [comment]
> just checked menuconfig: SHA256 is already implicitly selected by BT, WIRELESS, and a couple of others; thats probably why bitbakes minimal savedefconfig does not "report it separatly"

Please enter it explicitly, otherwise if dependent config options are removed at the later point in time - _RAUC_ will break, and we would not know why.

**Comment by js731ca** [comment]
that i would "NAK", since it conflicts with keeping the defconfig clean and minimal - by using 'bitbake -c savedefconfig'
how about adding a note to the commit that mentions that rauc also requires other switches that are implicitly on == check the (current) docs if in doubt

**Comment by zandrey** [comment]
> that i would "NAK", since it conflicts with keeping the defconfig clean and minimal - by using 'bitbake -c savedefconfig' how about adding a note to the commit that mentions that rauc also requires other switches that are implicitly on == check the (current) docs if in doubt

Nope, commit 4b4292cc7483b0403f798c4d9f98b1e4ffeba351 is incomplete as it does not **explicitly** includes all prerequisites for _RAUC_.

**Comment by js731ca** [comment]
if you're looking for completenes we would need to go with config fragments - or the mess thereof - in the metalayer...
('cause CONFIG_MD and CONFIG_SQUASHFS are also 'implicitly on' already.
and manually inserting all those just to toss them afterwards with a cleansing 'bitbake -c savedefconfig' seems pointless
my aim would be to keep the defconfig as lean as possible - to be better able to track changes made over time and link them to issues/features/...

**Comment by zandrey** [comment]
> if you're looking for completenes we would need to go with config fragments - or the mess thereof - in the metalayer... ('cause CONFIG_MD and CONFIG_SQUASHFS are also 'implicitly on' already. and manually inserting all those just to toss them afterwards with a cleansing 'bitbake -c savedefconfig' seems pointless my aim would be to keep the defconfig as lean as possible - to be better able to track changes made over time and link them to issues/features/...

Fragments (so as `bitbake` kernel config manipulations in general) would prohibit the standalone Kernel build/development flow. There are few users of the Kernel which are not bound to Yocto, therefore I would insist that Kernel development continues in this repo.

Kernel config options that are needed for this or the other feature shall be brought up explicitly in one PR, so that we have a possibility to track when and why certain options are enabled/disabled.

There shall be no assumptions made or implicit declarations assumed for config options that are required for a feature. All options are to be included explicitly.

**Comment by js731ca** [comment]
noticing that a 'savedefconfig' sanitization is already done on a regular basis (?); this PR should be good to go as-is

**Comment by js731ca** [comment]
rebased onto 6.1 -- but the first "normalize config" commit is concerning-ly large...
maybe we really should add this as a step when merging/updating upstream branches

**Review by zandrey — APPROVED** [review]

**Pull request merged**
