### PR TITLE
arm64: beluga_defconfig: enable dma-buf CMA heap

### PR DESCRIPTION
**Pull request by emfend**
Enable the dma-buf heap backed by the Contiguous Memory Allocator (CMA). This enables the allocation of physically contiguous memory from user space.
For beluga this allows a very efficient use of the DMA IP cores integrated in the FPGA. It is possible to allocate and directly map dma capable memory in the application software. Since the driver for the FPGA supports the import of such buffers, this area can be filled directly from the IP core. No further copying is necessary.

### CODE REVIEW

**Comment by zandrey** [comment]
@emfend Does this also require DTB carve-out?

@js731ca Please pick this one up into the Kernel config in layer once it is merged here.

**Comment by emfend** [comment]
The size of the area reserved for the CMA can be configured via a kernelconfig, a DTS entry, or a kernel command-line parameter.
Depending on how much memory the final system will eventually need, this will most likely require some adjustment. For the start, the default setting should be sufficient.

**Comment by emfend** [comment]
Ok, as there is another pending PR #126 which deletes the changed default configuration, I guess this PR is useless.

**Comment by zandrey** [comment]
> Ok, as there is another pending PR #126 which deletes the changed default configuration, I guess this PR is useless.

No, actually not! That is why it is assigned to @js731ca so he can pick this change up, either here or into the layer.

**Comment by js731ca** [comment]
> > Ok, as there is another pending PR #126 which deletes the changed default configuration, I guess this PR is useless.
> 
> No, actually not! That is why it is assigned to @js731ca so he can pick this change up, either here or into the layer.

"useless" nein - nur zwischen die Raeder gekommen
i created a PR in the meta layer where you guys can continue the review etc

**Comment by js731ca** [comment]
commit has been transplanted into a PR to the meta-layer

**Pull request closed without merging**
