### PR TITLE
Battery Fuel gauge bq78z100 for Crocodile

### PR DESCRIPTION
**Pull request by Qingwu-Li**
drivers:power:supply
    --Merged bq27xxx related driver from linux-5.9.12
    --Add BQ78Z100 Driver
crocodile_defconfig:
    --Set CONFIG_BATTERY_BQ27XXX_I2C
   --Clear CONFIG_BATTERY_SBS
crocodile.dts:
    --Add battery into i2c3

### CODE REVIEW

**Review by grembeter — CHANGES_REQUESTED** [review]
Hi Terry, why v5.9.12?
Could you please split this commit: cherry-pick commits for bq27xxx and a new commit for the new BQ78Z100.

**Comment by zandrey** [comment]
> 
> 
> Hi Terry, why v5.9.12?
> Could you please split this commit: cherry-pick commits for bq27xxx and a new commit for the new BQ78Z100.

Agree.

@Qingwu-Li
Please cherry-pick commits from upstream to add driver for `bq27xxx`. Do not pick them from stable kernel trees, as we would like to preserve original commits from _master_ for tracking purposes.

Use `git cherry-pick -x -s` in order to record the original commit id.

-- andrey

**Review by zandrey — CHANGES_REQUESTED** [review]
As I understand - commit 927a1c854964211325e8387e83b2bfdb4f14f3b1 can be directly submitted to upstream.

Please prepare it to be ready for submission (extend description, run trough `checkpatch.pl`, etc.) and then post it mainline.

Commit 7ef6de8d972a6e680bcfdcca66e6dc3e47cb602a requires more explanation on why you add one config option, and remove the other one.

**Comment by Qingwu-Li** [comment]
working on it

**Comment by Qingwu-Li** [comment]
@zandrey @grembeter Thanks a lot for input and knowlage share, I split into 3 comments, device tree and config will checkin later, this PR just battery driver relevant.

**Pull request closed without merging**
