### PR TITLE
arm64: crocodile_defconfig: enable usb storage

### PR DESCRIPTION
**Pull request by max186**
Add USB storage support to detect attached USB gadget devices as block devices.

Signed-off-by: Massimo Toscanelli <massimo.toscanelli@leica-geosystems.com>

### CODE REVIEW

**Comment by max186** [comment]
@zandrey, @Qingwu-Li shall I create a commit also for Beluga?

**Review by zandrey — APPROVED** [review]
This is already enabled in _Beluga_ via:
- 9907eec4ba8a `("arm64: beluga_defconfig: enable usb storage support")`
- a345474cff0c `("arm64: beluga_defconfig: add scsi block device support")`

Perhaps you can also consider porting dce0b588f8dd `("arm64: beluga_defconfig: enable microsoft fs support")` if _Crocodile_ requires this support.

**Comment by max186** [comment]
> This is already enabled in _Beluga_ via:
> 
> * [9907eec](https://github.com/hexagon-geo-surv/linux-leica/commit/9907eec4ba8a11c997fe38501ae21a6386ec8be4) `("arm64: beluga_defconfig: enable usb storage support")`
> * [a345474](https://github.com/hexagon-geo-surv/linux-leica/commit/a345474cff0ce24ea38c2f90cec5bfa37d8416e1) `("arm64: beluga_defconfig: add scsi block device support")`
> 
> Perhaps you can also consider porting [dce0b58](https://github.com/hexagon-geo-surv/linux-leica/commit/dce0b588f8ddf3828bae5fec059b00aa6389621f) `("arm64: beluga_defconfig: enable microsoft fs support")` if _Crocodile_ requires this support.

@htho-lgs what do you think about Microsoft FS support?, do we need it?

**Review by Qingwu-Li — APPROVED** [review]

**Comment by zandrey** [comment]
> > Perhaps you can also consider porting [dce0b58](https://github.com/hexagon-geo-surv/linux-leica/commit/dce0b588f8ddf3828bae5fec059b00aa6389621f) `("arm64: beluga_defconfig: enable microsoft fs support")` if _Crocodile_ requires this support.
> 
> @htho-lgs what do you think about Microsoft FS support?, do we need it?

Can be submitted with follow-up PR. I'll have this merged as-is now.

**Pull request merged**
