### PR TITLE
config: enable drivers for tilt module

### PR DESCRIPTION
**Pull request by mamtashukla**
Enable SCA3300 for Tilt IMU and BMI088 for VIS IMU

### CODE REVIEW

**Comment by zandrey** [comment]
@mamtashukla 

Is it relevant for all _KREA_ boards, or only new ones?

**Comment by zandrey** [comment]
Ah, I see. It is only targeting BLDC. Please discard the last comment. 👍🏻

**Comment by zandrey** [comment]
@grembeter I assign this on you, please merge once you check it.

**Review by grembeter — COMMENTED** [review]
@mamtashukla do you expect dts changes alongside? I would combine them in this PR.

**Pull request closed without merging**
