### PR TITLE
wifi/bt: test iw416 for wifi/bt is ok

### PR DESCRIPTION
**Pull request by lidaide**
test iw416 for wifi/bt is ok

### CODE REVIEW

**Review by zandrey — CHANGES_REQUESTED** [review]
NAK, contributions here should follow [Kernel Contribution Guidelines](https://www.kernel.org/doc/html/latest/process/submitting-patches.html).

Please format commits and describe changes in corresponding commit messages, see section [Describe your changes](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#describe-your-changes)

**Comment by zandrey** [comment]
@lidaide 

What is the difference in this PR comparing to #48? I see you try to push same commits with 2 PRs... Can you please close one of PRs and proceed with the single one?

**Comment by lidaide** [comment]
> 

@zandrey 
I will close this PR that based on crocodile-bringup branch, that is obsolete branch.

**Comment by lidaide** [comment]
I will close this PR that based on crocodile-bringup branch, that is obsolete branch. 
this function was finished based on the linux-5.15.y/crocodile branch.

**Pull request closed without merging**
