### PR TITLE
crocodile_defconfig: fix imx-sdma fw load

### PR DESCRIPTION
**Pull request by max186**
If the imx-sdma driver is built in the Kernel, the SDMA HW is probed when the firmware is not yet available.
So, we build the imx-sdma driver as a kernel module.

Signed-off-by: Massimo Toscanelli <massimo.toscanelli@leica-geosystems.com>

### CODE REVIEW

**Comment by max186** [comment]
@zandrey I did not verify the fw load in Beluga, but I assume it behaves in the same way, shall I create a patch for it?

**Review by zandrey — COMMENTED** [review]
Please adjust commit header, see https://github.com/hexagon-geo-surv/linux-leica/pull/89#pullrequestreview-1123346885

**Comment by zandrey** [comment]
@max186 

This has been fixed upstream in e95622289f26 `("arm64: defconfig: build imx-sdma as a module")`, please mention this in your commit and prepare the same for `beluga_defconfig`.

-- andrey

**Comment by max186** [comment]
v2:
- added upstream link in crocodile commit
- added commit to fix beluga

**Comment by max186** [comment]
v3: adjusted commit headers

**Comment by max186** [comment]
After discussion with @zandrey, we decided not to merge these changes that imply the usage of a Kernel module, but rather to  defer the driver probe keeping a monolithic Kernel.

**Comment by zandrey** [comment]
OK, I'll close this PR then.

**Pull request closed without merging**
