### PR TITLE
arm64: crocodile_defconfig: build in rtc and usb serial drv

### PR DESCRIPTION
**Pull request by max186**
Build the RTC and USB serial drivers in the Kernel aiming to obtain a monolithic Kernel.

Signed-off-by: Massimo Toscanelli <massimo.toscanelli@leica-geosystems.com>

### CODE REVIEW

**Comment by zandrey** [comment]
Shall this be rather part of compete attempt to build a monolithic Kernel? Why is _RTC_ a special case here?

**Comment by max186** [comment]
> Shall this be rather part of compete attempt to build a monolithic Kernel? Why is _RTC_ a special case here?

This is what I meant, that we want to build it as part of the monolithic Kernel and in fact, the RTC should not be a special case, as it was before as a module.
It was built as a module because in our tests for the RTC backup battery I was unloading the module, reading the register values via I2C and then reloading it. We will probably need to introduce the functionality in the driver, if a real test of the battery is still required.

**Comment by max186** [comment]
V2:
Added commit to build in the Kernel the USB serial driver.

The RTC and the USB serial are the only 2 Kernel modules that are currently loaded. Therefore, we can decide to build them in the Kernel aiming to obtain a monolithic one.

The rest of the clean up (removing unused modules or building them in), can be performed once we have better understanding of the application requirements.

**Review by zandrey — APPROVED** [review]

**Comment by js731ca** [comment]
> The rest of the clean up (removing unused modules or building them in), can be performed once we have better understanding of the application requirements.

starting of with a all-no-config and only pulling in the minimal set of configs to get the board booting would have avoided all the work of stripping it down again...
since beluga is in still earlier stages than crocodile: would it make sense to adopt this strategy there?

**Comment by zandrey** [comment]
> > The rest of the clean up (removing unused modules or building them in), can be performed once we have better understanding of the application requirements.
> 
> starting of with a all-no-config and only pulling in the minimal set of configs to get the board booting would have avoided all the work of stripping it down again... @htho-lgs @zandrey : since beluga is in still earlier stages than crocodile: would it make sense to adopt this strategy there?

That would be a fair deal IMO.

**Pull request merged**
