### PR TITLE
Sync master with Linux master

### PR DESCRIPTION
**Pull request by bith3ad**
The master branch was synced long time ago...

### CODE REVIEW

**Comment by bith3ad** [comment]
@zandrey Please setup a sync job for master as well.

**Comment by Emantor** [comment]
10.000 commits. Not bad. :smile:

**Comment by zandrey** [comment]
> 10.000 commits. Not bad. 😄

Indeed! 😆 

As @bith3ad suggested, I would setup the sync job for `master` branch as well. Thanks for pointing it out!

-- andrey

**Comment by zandrey** [comment]
> @zandrey Please setup a sync job for master as well.

I guess we can drop this PR if it only contains upstream work. I would pull it through the sync, and setup the regular updates.

How's that sound?

**Pull request merged**
